#!/bin/sh

case "$1" in
	start)
    modprobe hello
		../../usr/bin/scull_load
		../../usr/bin/module_load faulty
		../../usr/bin/module_load aesdchar
		;;
	stop)
		../../usr/bin/module_unload aesdchar
		../../usr/bin/module_unload faulty
		../../usr/bin/scull_unload
		rmmod hello
		;;
    *)
		echo "Usage: $0 {start|stop}"
		exit 1
esac
