#!/bin/sh

#DIR_PATH=$(dirname $(readlink -f "${BASH_SOURCE:-$0}"))
target=10.0.2.2
port=9000

system_data_folder="/var/log/system_monitor/$(date '+%Y_%m_%d_%H_%M_%S')"
mkdir -p "${system_data_folder}"

system_data_file_cpu_mem="${system_data_folder}/cpu_mem"
system_data_file_disk="${system_data_folder}/disk"
system_data_file_network="${system_data_folder}/network"

top -b -d 1 | tee ${system_data_file_cpu_mem} | nc ${target} ${port} -w 1 &
iotop -b -o -d 1 | tee ${system_data_file_disk} | nc ${target} ${port} -w 1 &
iftop -t -B | tee ${system_data_file_network} | nc ${target} ${port} -w 1 &
# sensors command can be executed correctly in QEMU environment
#sensors >> ${system_data_file_temperature
